[package]
authors = ["The Gtk-rs Project Developers"]
categories = ["api-bindings", "gui"]
description = "Macros helpers for GTK 4 bindings"
documentation = "https://gtk-rs.org/gtk4-rs/stable/docs/gtk4_macros"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gtk", "gtk4", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gtk4-macros"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
heck = "0.3"
itertools = "0.10"
proc-macro-crate = "1.0"
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", default-features = false, features = ["full"]}
