[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "Rust bindings of the GDK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/docs/gdk4/"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gdk", "gdk4", "gtk", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gdk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[lib]
name = "gdk4"

[features]
dox = ["ffi/dox", "glib/dox", "gio/dox", "gdk-pixbuf/dox", "cairo-rs/dox", "pango/dox"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/embed-lgpl-docs", "gdk-pixbuf/embed-lgpl-docs", "gio/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "cairo-rs/purge-lgpl-docs", "gdk-pixbuf/purge-lgpl-docs", "gio/purge-lgpl-docs"]
v4_2 = ["ffi/v4_2"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[dependencies]
bitflags = "1.0"
cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_14"]}
ffi = {package = "gdk4-sys", path = "./sys"}
gdk-pixbuf = {git = "https://github.com/gtk-rs/gtk-rs"}
gio = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
glib = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
libc = "0.2"
pango = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_46"]}

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
optional = true
version = "0.1.3"

[dev-dependencies]
gir-format-check = "^0.1"
