[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "Rust bindings of the GDK4 X11 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/docs/gdk4_x11/"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gdk", "gdk4", "gdk4-x11", "gtk", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gdk4-x11"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[features]
dox = ["ffi/dox"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[dependencies]
ffi = {path = "./sys", package = "gdk4-x11-sys"}
gdk = {path = "../gdk4", package = "gdk4"}
gio = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
glib = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
libc = "0.2"
x11 = "2.18"

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
optional = true
version = "0.1.3"

[dev-dependencies]
gir-format-check = "^0.1"
