[package]
name = "gdk4-x11-sys"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"
build = "build.rs"
[package.metadata.system-deps.gtk4_x11]
name = "gtk4-x11"
version = "4.0.0"
[package.metadata.docs.rs]
features = ["dox"]

[lib]
name = "gdk4_x11_sys"

[dependencies]
libc = "0.2"
x11 = "2.18"

[dependencies.gdk4-sys]
path = "../../gdk4/sys"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/gtk-rs.git"

[build-dependencies]
system-deps = "3"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = []
