[package]
authors = ["The gtk-rs Project Developers"]
description = "Rust bindings of the GSK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gsk4"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gsk", "gsk4", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gsk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.2.0"

[lib]
name = "gsk4"

[features]
broadway = []
dox = ["ffi/dox", "gdk/dox", "graphene/dox", "glib/dox", "cairo-rs/dox", "pango/dox"]
v4_2 = ["ffi/v4_2", "gdk/v4_2"]
vulkan = []

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
bitflags = "1.0"
cairo-rs = "0.14"
ffi = {package = "gsk4-sys", path = "./sys", version = "0.2.0"}
gdk = {package = "gdk4", path = "../gdk4", version = "0.2.0"}
glib = {version = "0.14", features = ["v2_66"]}
graphene = {package = "graphene-rs", version = "0.14"}
libc = "0.2"
pango = {version = "0.14", features = ["v1_46"]}

[dev-dependencies]
gir-format-check = "^0.1"
