[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "Rust bindings of the GSK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/docs/gsk4"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gsk", "gsk4", "gtk", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gsk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[lib]
name = "gsk4"

[features]
broadway = []
dox = ["ffi/dox", "gdk/dox", "graphene/dox", "glib/dox", "cairo-rs/dox", "pango/dox"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs", "graphene/embed-lgpl-docs", "cairo-rs/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs", "graphene/purge-lgpl-docs", "cairo-rs/purge-lgpl-docs"]
v4_2 = ["ffi/v4_2", "gdk/v4_2"]
vulkan = []

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[dependencies]
bitflags = "1.0"
cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_14"]}
ffi = {package = "gsk4-sys", path = "./sys"}
gdk = {package = "gdk4", path = "../gdk4"}
glib = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
graphene = {package = "graphene-rs", git = "https://github.com/gtk-rs/gtk-rs"}
libc = "0.2"
pango = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_46"]}

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
optional = true
version = "0.1.3"

[dev-dependencies]
gir-format-check = "^0.1"
