[package]
name = "gsk4"
license = "MIT"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
keywords = ["gsk", "gsk4", "gtk", "gtk-rs", "gnome", "GUI"]
readme = "README.md"
documentation = "https://gtk-rs.org/docs/gsk4/"
version = "0.1.0"
description = "Rust bindings for the GSK 4 library"
repository = "https://github.com/gtk-rs/gsk4"
build = "build.rs"
edition = "2018"
exclude = [
    "gir-files/*",
]

[lib]
name = "gsk4"

[features]
dox = ["ffi/dox", "gdk/dox", "graphene/dox", "glib/dox", "cairo-rs/dox", "pango/dox"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs", "graphene/purge-lgpl-docs", "cairo-rs/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs", "graphene/embed-lgpl-docs", "cairo-rs/embed-lgpl-docs"]
vulkan = []
broadway = []
v4_2 = ["ffi/v4_2", "gdk/v4_2"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
ffi = { package = "gsk4-sys", path = "./sys" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs" }
glib = { git = "https://github.com/gtk-rs/gtk-rs" }
gdk = { package = "gdk4", path = "../gdk4" }
graphene = { package = "graphene-rs", git = "https://github.com/gtk-rs/gtk-rs" }
pango = { git = "https://github.com/gtk-rs/gtk-rs" }

[dev-dependencies]
gir-format-check = "^0.1"
