[package]
authors = ["The gtk-rs Project Developers"]
categories = ["api-bindings", "gui"]
description = "Rust bindings of the GTK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gtk", "gtk4", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gtk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.2.0"

[lib]
name = "gtk4"

[features]
dox = ["gdk/dox", "gsk/dox", "ffi/dox"]
v4_2 = ["ffi/v4_2", "gdk/v4_2", "gsk/v4_2"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
bitflags = "1.0"
cairo-rs = "0.14"
ffi = {package = "gtk4-sys", path = "./sys"}
field-offset = "0.3"
futures-channel = "0.3"
gdk = {package = "gdk4", path = "../gdk4"}
gdk-pixbuf = "0.14"
gio = {version = "0.14", features = ["v2_66"]}
glib = {version = "0.14", features = ["v2_66"]}
graphene = {package = "graphene-rs", version = "0.14"}
gsk = {package = "gsk4", path = "../gsk4"}
gtk4-macros = {path = "../gtk4-macros"}
libc = "0.2"
once_cell = "1.0"
pango = {version = "0.14", features = ["v1_46"]}

[dev-dependencies]
gir-format-check = "^0.1"
