[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
categories = ["api-bindings", "gui"]
description = "Rust bindings of the GTK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/docs/gtk4"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gtk", "gtk4", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gtk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[lib]
name = "gtk4"

[features]
dox = ["gdk/dox", "gsk/dox", "ffi/dox", "x11", "wayland"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs", "gsk/embed-lgpl-docs"]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs", "gsk/purge-lgpl-docs"]
v4_2 = ["ffi/v4_2", "gdk/v4_2", "gsk/v4_2"]
wayland = ["gdk-wayland"]
x11 = ["gdk-x11"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[dependencies]
bitflags = "1.0"
cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_14"]}
ffi = {package = "gtk4-sys", path = "./sys"}
field-offset = "0.3"
futures-channel = "0.3"
gdk = {package = "gdk4", path = "../gdk4"}
gdk-pixbuf = {git = "https://github.com/gtk-rs/gtk-rs"}
gdk-wayland = {package = "gdk4-wayland", path = "../gdk4-wayland", optional = true}
gdk-x11 = {package = "gdk4-x11", path = "../gdk4-x11", optional = true}
gio = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
glib = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_66"]}
graphene = {package = "graphene-rs", git = "https://github.com/gtk-rs/gtk-rs"}
gsk = {package = "gsk4", path = "../gsk4"}
gtk4-macros = {path = "../gtk4-macros"}
libc = "0.2"
once_cell = "1.0"
pango = {git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_46"]}

[build-dependencies.gtk-rs-lgpl-docs]
git = "https://github.com/gtk-rs/lgpl-docs"
optional = true
version = "0.1.3"

[dev-dependencies]
gir-format-check = "^0.1"
