[package]
documentation = "https://gtk-rs.org/docs/gtk4/"
categories = ["api-bindings", "gui"]
license = "MIT"
description = "Rust bindings for the GTK 4 library"
name = "gtk4"
homepage = "https://gtk-rs.org/"
authors = ["The Gtk-rs Project Developers"]
readme = "README.md"
version = "0.1.0"
keywords = ["gtk", "gtk4", "gtk-rs", "gnome", "GUI"]
repository = "https://github.com/gtk-rs/gtk4"
build = "build.rs"
edition = "2018"
exclude = [
    "gir-files/*",
]

[lib]
name = "gtk4"

[features]
purge-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/purge-lgpl-docs", "gsk/purge-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs", "gdk/embed-lgpl-docs", "gsk/embed-lgpl-docs"]
dox = ["gdk/dox", "gsk/dox", "ffi/dox"]
x11 = ["gdk-x11"]
wayland = ["gdk-wayland"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
bitflags = "1.0"
field-offset = "0.3"
futures-channel = "0.3"
once_cell = "1.0"
ffi =  { package = "gtk4-sys", path = "./sys" }
gtk4-macros =  { path = "../gtk4-macros" }
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs" }
gio = { git = "https://github.com/gtk-rs/gtk-rs", features = ["v2_46"] }
glib = { git = "https://github.com/gtk-rs/gtk-rs" }
gdk = { package = "gdk4", path = "../gdk4" }
graphene = { package = "graphene-rs", git = "https://github.com/gtk-rs/gtk-rs" }
gsk = { package = "gsk4", path = "../gsk4" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gtk-rs" }
pango = { git = "https://github.com/gtk-rs/gtk-rs", features = ["v1_46"] }
gdk-x11 = { package = "gdk4-x11", path = "../gdk4-x11", optional = true}
gdk-wayland = { package = "gdk4-wayland", path = "../gdk4-wayland", optional = true}

[dev-dependencies]
gir-format-check = "^0.1"
