[options]
work_mode = "sys"
library = "Gdk"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "GdkPixbuf",
    "Pango",
    "Cairo",
]
