[package]
name = "gtk4-rs-examples"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]
edition = "2018"

[dependencies]
chrono = "0.4.19"

[dependencies.gtk]
path = "../gtk4"
package = "gtk4"
