[package]
name = "gtk4-rs-examples"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]
edition = "2018"
autobins = false

[dependencies]
chrono = "0.4.19"

[dependencies.gtk]
path = "../gtk4"
package = "gtk4"

[[bin]]
name = "basic"

[[bin]]
name = "builder_basics"

[[bin]]
name = "builders"

[[bin]]
name = "clock"

[[bin]]
name = "composite_template"

[[bin]]
name = "css"

[[bin]]
name = "entry_completion"

[[bin]]
name = "text_viewer"

[[bin]]
name = "widget_subclass"
