[package]
authors = ["The gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings of GSK 4"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gsk4_sys/"
edition = "2018"
homepage = "http://gtk-rs.org/"
keywords = ["gsk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
name = "gsk4-sys"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.2.0"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.gtk4]
name = "gtk4"
version = "4.0.0"

[package.metadata.system-deps.gtk4.v4_2]
version = "4.1.2"

[lib]
name = "gsk4_sys"

[features]
dox = []
v4_2 = []

[dependencies]
libc = "0.2"

[dependencies.cairo-sys-rs]
version = "0.14"

[dependencies.gdk4-sys]
path = "../../gdk4/sys"

[dependencies.glib-sys]
version = "0.14"

[dependencies.gobject-sys]
version = "0.14"

[dependencies.graphene-sys]
version = "0.14"

[dependencies.pango-sys]
version = "0.14"

[build-dependencies]
system-deps = "3"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"
