name: book

on:
  pull_request:
  push:
    branches:
      - "master"
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: listings build
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo build
        working-directory: book/listings

  build-deploy:
    runs-on: ubuntu-20.04
    name: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1

      - run: mdbook build -d public
        working-directory: book
      - run: echo "DEST=$(if [ "$GITHUB_EVENT_NAME" == "release" ]; then echo 'stable'; else echo 'git'; fi)" >> ${GITHUB_ENV}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/public
          keep_files: false
          destination_dir: ${{ env.DEST }}/book

  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: book
