on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.51.0"
        conf:
          - { name: "gtk4", features: "v4_2", test_sys: false }
          - { name: "gsk4", features: "v4_2,broadway,vulkan", test_sys: true }
          - { name: "gdk4", features: "v4_2", test_sys: true }
          - { name: "gdk4-wayland", features: "", test_sys: true }
          - { name: "gdk4-x11", features: "", test_sys: false }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: "${{ matrix.conf.name }}: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}"
      - name: "${{ matrix.conf.name }}/sys: tests"
        run: xvfb-run --auto-servernum cargo test --manifest-path ${{ matrix.conf.name }}/sys/Cargo.toml
        if: matrix.conf.test_sys
      - name: "${{ matrix.conf.name }}: build"
        run: cargo build --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}"

      - run: rustup component add clippy
        if: matrix.rust == 'stable'
      - run: cargo clippy --manifest-path ${{ matrix.conf.name }}/Cargo.toml --features "${{ matrix.conf.features }}" --all-targets -- -D warnings
        if: matrix.rust == 'stable'

      - uses: bcomnes/cleanup-xvfb@v1

  examples:
    name: examples
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: "examples: build"
        run: cargo build --manifest-path examples/Cargo.toml --bins --examples --all-features
      - name: "examples: clippy"
        run: cargo clippy --manifest-path examples/Cargo.toml --all-targets -- -D warnings

  fmt:
    name: rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  regen_check:
    name: regen checker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - run: python3 ./generator.py --yes ./
      - run: git diff --exit-code

  checker:
    name: gtk-rs checker
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        crate:
          - gdk4
          - gdk4-x11
          - gdk4-wayland
          - gsk4
          - gtk4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gtk-rs/checker
          ref: master
          path: checker
      - working-directory: checker
        run: cargo build --release
      - run: cargo run -- ../${{matrix.crate}}
        working-directory: checker
      - run: cargo run -- ../${{matrix.crate}}/sys
        working-directory: checker
      - run: ./check_init_asserts ../${{matrix.crate}}
        working-directory: checker
      - name: Check doc aliases
        run: |
          python3 doc_aliases.py ../${{matrix.crate}}
          cd .. && git diff --exit-code
        working-directory: checker

  checker-macros:
    name: gtk-rs macro checker
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        crate:
          - gtk4-macros
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: gtk-rs/checker
          ref: master
          path: checker
      - working-directory: checker
        run: cargo build --release
      - run: cargo run -- --no-manual-traits ../${{matrix.crate}}
        working-directory: checker
