name: docs

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    name: build
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - working-directory: gir
        run: cargo build --release
      - run: rustup component add rustfmt
      - run: cargo install rustdoc-stripper
      - run: python3 ./generator.py --embed-docs --yes ./
      - run: echo "DEST=$(if [ "$GITHUB_EVENT_NAME" == "release" ]; then echo 'stable'; else echo 'git'; fi)" >> ${GITHUB_ENV}
      - uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: |
            -Z unstable-options --enable-index-page 
            --extern-html-root-url=glib=https://gtk-rs.org/gtk-rs/${{ env.DEST }}/docs/ 
            --extern-html-root-url=gio=https://gtk-rs.org/gtk-rs/${{ env.DEST }}/docs/ 
            --extern-html-root-url=cairo=https://gtk-rs.org/gtk-rs/${{ env.DEST }}/docs/ 
            --extern-html-root-url=gdk_pixbuf=https://gtk-rs.org/gtk-rs/${{ env.DEST }}/docs/ 
            --extern-html-root-url=graphene=https://gtk-rs.org/gtk-rs/${{ env.DEST }}/docs/ 
            --extern-html-root-url=pango=https://gtk-rs.org/gtk-rs/${{ env.DEST }}/docs/ 
            --extern-html-root-url=wayland_client=https://smithay.github.io/wayland-rs/ 
            --extern-html-root-url=x11=https://docs.rs/x11/latest/
        with:
          command: doc
          args: -p gdk4 -p gdk4-sys -p gdk4-wayland -p gdk4-wayland-sys -p gdk4-x11 -p gdk4-x11-sys -p gsk4 -p gsk4-sys -p gtk4 -p gtk4-sys -p gtk4-macros --features "dox" --no-deps
      - name: GTK Docs Images
        run: |
          git clone --depth=1 https://gitlab.gnome.org/GNOME/gtk --no-checkout ./gtk-src
          cd ./gtk-src
          git sparse-checkout init --cone
          git sparse-checkout set docs/reference/gtk/images
          git checkout master
          mv ./docs/reference/gtk/images/*.png ./target/doc/gtk4
          
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'release' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
          keep_files: false
          destination_dir: ${{ env.DEST }}/docs
